## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.6
#  - nightly
notifications:
  email: false
git:
  depth: 99999999


## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("SimpleLife"); Pkg.test("SimpleLife"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("SimpleLife")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("SimpleLife")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
